In [15]:
import numpy as np

numeros = np.array([1, 2, 3, 4, 5])

ceros = np.zeros(5)

unos = np.ones(5)

aleatorios = np.random.rand(5)

print(numeros[1:4])

type(ceros)

a = np.array([1,2,3])

b = np.array([10,20,30])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a*2)
print(a**2)

notas = np.array([6,8,9,10,5,7])
print('Media:', notas.mean())

print('Máximo:', notas.max())

print('Mínimo:', notas.min())

print('Suma:', notas.sum())

print('Desviación estándar:', notas.std())

num1 =np.array([5,10,15,20,25])

print('Suma: ', num1.sum())
print('Máximo:', num1.max())
print('Mínimo:', num1.min())
print('Media:', num1.mean())
print('Multiplicación: ', num1*3)

[2 3 4]
[11 22 33]
[ -9 -18 -27]
[10 40 90]
[0.1 0.1 0.1]
[2 4 6]
[1 4 9]
Media: 7.5
Máximo: 10
Mínimo: 5
Suma: 45
Desviación estándar: 1.707825127659933
Suma:  75
Máximo: 25
Mínimo: 5
Media: 15.0
Multiplicación:  [15 30 45 60 75]
